name: Multi dimention Matrix
on: push
jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        version: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          nodeversion: ${{ matrix.version }}
      - run: echo "${RUNNER_OS}" && node --version
