name: Change shell
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref}}
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: echo "${SHELL}"
      - shell: python
        run: |
          import os
          print(os.environ['PATH'])
